language: node_js
install:
- npm install -g codecov
- npm install
script:
- npm test
- codecov
node_js:
- v6
sudo: false
deploy:
  provider: npm
  email: pranav.r.parikh@gmail.com
  api_key:
    secure: CTy51gHMF6ctIGD4V4CaGwfnk0J2x4NsRNAmMvMjFv1QPQunXuuxigyP5NIfBZgYUyBMf01fvSADTuuSBb2OJKEQg0VglLOMbyCSH6D9AXcEBmvsvb2AVBDz6+0y86tKdgBHpI7OKbGTWa7xRYVP1xqt5eP9tIzxK29M2rXzIjLUY1E4DfQaDp6RPIBUTEkd4SZ+jtZ7x4KrWJpUa9Jk5FmfL53GUk+EnQG3TJ0E2aCacLA7hr225y1mbKQ+ygRvQs9j/0Efj5tPqxJQcV5aEjs/IKS8DSXsCtGpzPUGD1aXNfo5tgCatg+BzD9jh0eXfmKDUBTSDJRiiP22TNf69KEVs/HXfi42kcS9XBhbu2WtT6hpADp7f0cjpjDmhs4XpKudGuVib2TgsqR2ot2HVJdiyWxk+iHC3oiLvl+gmuJFlRPbadspIFLKH3uJXNZ5JuHMaBsgLc9PA5NCUqsJboOi6MVPkdoS5J6JGB8qk4pKt2+Pa0oho3yYqG27kDKoLJFJdPbVVMw2WRMjQwqwXQ26z6qsxq2hdlHKqbEtkVcuBVDQzCj3h+wgbrBmFoVozQnU2cbVpcoOV492+9lrBQIWYtrQu8vZ9AAuXN01FsCxQHgtsB3qawb0LDWH6fxke4+tL5eAz1J7/BJkCRLrkJRBKV6yjVzlPnbSnpHQh9s=
  on:
    tags: true
    repo: TestArmada/shifu-util
