language: node_js
install:
- npm install -g codecov
- npm install
script:
- npm test
- codecov
node_js:
- v6
sudo: false
deploy:
  provider: npm
  email: pranav.r.parikh@gmail.com
  api_key:
    secure: NAqDQr51Y8UItJDw0GI97xxWXczJ5MFRD6QgOPN4FAJvsE3csZegkvCq1bGS3aOb6Zy75cBy4tUslc/DcUEPtDlAr49iDUq46J3phQDAKlu6WUYwJp1k8LEUjfj0fjfZ711MfMD1TrJ4axTji+2s1PSWr6dpGuiV7fUad7Lv3aLv3TrIYleq0Nub7HRI4RYeFyPM9WWLYdPOTLpSkbfZOyjUrCtFG1e65aEVyQxHkvFynvuwIwxqyNyFydi8JpT+UU1/wmFH+Xy6RFDQW4fTnNQNTWte/LwppHoRrTUZ0Ea5VVS63k+dsLDN+qqfmPVi/iPM2sIhqEZzrb+uVFFI+TEosTs0D1fbZjM50hM+XYNnlm6nArivILBSbvH7RyP+lRcRA80+U7nW730hOi+9Me+LJMS+IBsVEJI1jM3qblcU2iaYsNmEaTfITwsk4Pxh/48p2iBhLJFSQmzH9m2lsV+fPems8ld5WBW1GRrS+fEpwQqoxu6VoqaHdqLpyzJyWLd5upQDJLzwZN36CkDme0TuKv9SuSvqkILfusg9XhySNIEGyotBHxOJSWsSKR6dO9IGiK1k7U35crpA5SlXgJu+Mt+UzwqyB1ILlgnwmD13/rYyNkSeHWgKeifc67D6kde49qDfrEX1Td8a0sBJF7JuRMh8Ka93S7RWQKKmieI=
  on:
    tags: true
    repo: TestArmada/shifu-util
